"""add buyer criteria profiles and assessments

Revision ID: 3eee634a1c76
Revises: e19c46bd2fd0
Create Date: 2026-07-21 14:14:21.086966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eee634a1c76'
down_revision: Union[str, Sequence[str], None] = 'e19c46bd2fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_criteria_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('aspects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_criteria_profile_slug')
    )
    op.create_table('criteria_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['buyer_criteria_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Batch mode + explicitly named constraints: SQLite has no ALTER TABLE ADD CONSTRAINT,
    # so Alembic must rebuild the table, and an unnamed constraint couldn't be dropped
    # again on downgrade.
    with op.batch_alter_table('analyses') as batch_op:
        batch_op.add_column(sa.Column('criteria_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_analyses_criteria_profile_id', 'buyer_criteria_profiles',
            ['criteria_profile_id'], ['id'],
        )
    with op.batch_alter_table('search_runs') as batch_op:
        batch_op.add_column(sa.Column('criteria_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_search_runs_criteria_profile_id', 'buyer_criteria_profiles',
            ['criteria_profile_id'], ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_runs') as batch_op:
        batch_op.drop_constraint('fk_search_runs_criteria_profile_id', type_='foreignkey')
        batch_op.drop_column('criteria_profile_id')
    with op.batch_alter_table('analyses') as batch_op:
        batch_op.drop_constraint('fk_analyses_criteria_profile_id', type_='foreignkey')
        batch_op.drop_column('criteria_profile_id')
    op.drop_table('criteria_assessments')
    op.drop_table('buyer_criteria_profiles')
    # ### end Alembic commands ###
