"""drop unused VehicleIdentity.power_kw

Revision ID: 50f9532be7ea
Revises: 5b9ee009016e
Create Date: 2026-07-09 10:43:14.038847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f9532be7ea'
down_revision: Union[str, Sequence[str], None] = '5b9ee009016e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_identities', 'power_kw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_identities', sa.Column('power_kw', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
