"""add analysis confidence and score_breakdown

Revision ID: 5b9ee009016e
Revises: 63b4f579d780
Create Date: 2026-07-08 10:26:14.647368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9ee009016e'
down_revision: Union[str, Sequence[str], None] = '63b4f579d780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('score_breakdown', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('analyses', sa.Column('confidence', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'confidence')
    op.drop_column('analyses', 'score_breakdown')
    # ### end Alembic commands ###
